routes/signup.py
# Import necessary modules and functions
from modules import (
    Log,  # Logging module
    ssl,  # SSL/TLS module
    abort,  # Function for aborting requests
    flash,  # Flash messaging module
    session,  # Session management module
    sqlite3,  # SQLite database module
    request,  # Module for handling HTTP requests
    smtplib,  # SMTP client module
    redirect,  # Function for redirecting requests
    APP_NAME,  # Constant for application name
    SMTP_PORT,  # SMTP port number
    SMTP_MAIL,  # SMTP email address
    RECAPTCHA,  # Recaptcha module
    addPoints,  # Function for adding points to user
    Blueprint,  # Blueprint class for creating modular applications
    encryption,  # Encryption module
    SignUpForm,  # Form for user sign-up
    SMTP_SERVER,  # SMTP server address
    EmailMessage,  # Class for creating email messages
    requestsPost,  # Module for making HTTP POST requests
    REGISTRATION,  # Flag for enabling/disabling user registration
    SMTP_PASSWORD,  # SMTP password
    DB_USERS_ROOT,  # Path to the users database
    render_template,  # Function for rendering templates
    currentTimeStamp,  # Function for getting current timestamp
    RECAPTCHA_SIGN_UP,  # Flag for enabling/disabling Recaptcha for sign-up
    RECAPTCHA_SITE_KEY,  # Recaptcha site key
    RECAPTCHA_VERIFY_URL,  # Recaptcha verification URL
    RECAPTCHA_SECRET_KEY,  # Recaptcha secret key
)

# Create a blueprint for the signup route
signUpBlueprint = Blueprint("signup", __name__)


# Define the route handler for the signup page
@signUpBlueprint.route("/signup", methods=["GET", "POST"])
def signup():
    """
    This function handles the sign up route.

    If the user is already signed in, they will be redirected to the homepage.
    If the user submits the sign up form, their information is checked to ensure it is valid.
    If the information is valid, their account is created and they are signed in.

    Returns:
    The sign up page with any errors or a confirmation message.
    """
    # Check if registration is enabled
    match REGISTRATION:
        # If registration is enabled
        case True:
            # Check if the user is already logged in
            match "userName" in session:
                # If user is already logged in, redirect to homepage
                case True:
                    Log.danger(f'USER: "{session["userName"]}" ALREADY LOGGED IN')
                    return redirect("/")
                # If user is not logged in
                case False:
                    # Create sign up form object
                    form = SignUpForm(request.form)
                    # Check if request method is POST (form submitted)
                    match request.method == "POST":
                        # If form is submitted
                        case True:
                            # Extract form data
                            userName = request.form["userName"]
                            email = request.form["email"]
                            password = request.form["password"]
                            passwordConfirm = request.form["passwordConfirm"]
                            # Remove spaces from username
                            userName = userName.replace(" ", "")
                            Log.sql(
                                f"Connecting to '{DB_USERS_ROOT}' database"
                            )  # Log the database connection is started
                            # Connect to the database
                            connection = sqlite3.connect(DB_USERS_ROOT)
                            connection.set_trace_callback(
                                Log.sql
                            )  # Set the trace callback for the connection
                            cursor = connection.cursor()
                            # Fetch existing usernames and emails from the database
                            cursor.execute("select userName from users")
                            users = str(cursor.fetchall())
                            cursor.execute("select email from users")
                            mails = str(cursor.fetchall())
                            # Check if username and email are available
                            match not userName in users and not email in mails:
                                # If username and email are available
                                case True:
                                    # Check if passwords match
                                    match passwordConfirm == password:
                                        # If passwords match
                                        case True:
                                            # Check if username contains only ASCII characters
                                            match userName.isascii():
                                                # If username contains only ASCII characters
                                                case True:
                                                    # Hash the password
                                                    password = encryption.hash(password)
                                                    # Connect to the database
                                                    connection = sqlite3.connect(
                                                        DB_USERS_ROOT
                                                    )
                                                    connection.set_trace_callback(
                                                        Log.sql
                                                    )  # Set the trace callback for the connection
                                                    # Check if reCAPTCHA is enabled for sign up
                                                    match RECAPTCHA and RECAPTCHA_SIGN_UP:
                                                        # If reCAPTCHA is enabled
                                                        case True:
                                                            # Verify reCAPTCHA response
                                                            secretResponse = request.form[
                                                                "g-recaptcha-response"
                                                            ]
                                                            verifyResponse = requestsPost(
                                                                url=f"{RECAPTCHA_VERIFY_URL}?secret={RECAPTCHA_SECRET_KEY}&response={secretResponse}"
                                                            ).json()
                                                            # If reCAPTCHA verification is successful
                                                            match verifyResponse[
                                                                "success"
                                                            ] == True or verifyResponse[
                                                                "score"
                                                            ] > 0.5:
                                                                # If reCAPTCHA verification is successful
                                                                case True:
                                                                    Log.success(
                                                                        f"Sign up reCAPTCHA | verification: {verifyResponse['success']} | verification score: {verifyResponse['score']}",
                                                                    )
                                                                    # Insert user data into the database
                                                                    cursor = (
                                                                        connection.cursor()
                                                                    )
                                                                    cursor.execute(
                                                                        f"""
                                                                        insert into users(userName,email,password,profilePicture,role,points,timeStamp,isVerified) \
                                                                        values(?, ?, ?, ?, ?, ?, ?, ?)
                                                                        """,
                                                                        (
                                                                            userName,
                                                                            email,
                                                                            password,
                                                                            f"https://api.dicebear.com/7.x/identicon/svg?seed={userName}&radius=10",
                                                                            "user",
                                                                            0,
                                                                            currentTimeStamp(),
                                                                            "False",
                                                                        ),
                                                                    )
                                                                    connection.commit()
                                                                    # Log user addition
                                                                    Log.success(
                                                                        f'User: "{userName}" added to database',
                                                                    )

templates/tailwindUI/about.html.jinja
{% extends 'layout.html.jinja' %}
{% block head %}
<!-- Set the title of the About page with the app name -->
<title>About {{ appName }}</title>
{% endblock head %}

{% block body %}
<!-- Container for the About page content -->
<div class="w-10/12 md:w-4/6 lg:w-6/12 xl:w-5/12 mx-auto mt-20 md:mt-32 break-words text-center text-lg">

  <!-- Link to the main page of the app -->
  <a class="text-rose-500 text-4xl font-bold select-none" href="https://dogukanurker.com/flaskblog" target="_blank">
    {{ appName }}
  </a>

  <!-- Version of the app -->
  <div class="mt-1 text-xs">
    Version: {{ appVersion }}
  </div>

  <!-- Description of the blog app -->
  <div class="mt-4 mx-auto">
    Simple blog app made with Flask, SQLite3, WTForms, Passlib, reCAPTCHA, Requests, TailwindCSS, Tabler Icons
  </div>

  <!-- Link to the GitHub repository of the app -->
  <div class="mt-4 mx-auto">
    <a href="https://github.com/DogukanUrker/flaskBlog" target="_blank">
      Click for more information about
      <p class="text-rose-500 inline-block">{{ appName }}</p>
      on
      <p class="inline-block">GitHub <i class="ti ti-brand-github"></i></p>
    </a>
  </div>

  <!-- Credits and source repo information -->
  <!-- Please respect this code’s originality and credit the original repo. Thanks for your cooperation. 💜 -->
  <div class="mx-auto text-xs absolute bottom-2 left-0 right-0 select-none">
    <a href="https://github.com/DogukanUrker/flaskBlog" target="_blank" class="text-rose-500 font-medium block">source
      repo</a>
    Made with <i class="ti ti-heart-filled text-rose-500"></i> by
    <a href="https://dogukanurker.com/" target="_blank" class="text-rose-500 font-medium">Dogukan Urker</a>
  </div>
</div>
{% endblock body %}

templates/tailwindUI/accountSettings.html.jinja
{% extends 'layout.html.jinja' %}
{% block head %}
<!-- Set the title of the Account Settings page -->
<title>Account Settings</title>
{% endblock head %}

{% block body %}
<!-- Container for the Account Settings content -->
<div class="w-fit mx-auto mt-32 text-center text-2xl font-medium">

  <!-- Link to change username page -->
  <h2 class="my-4">
    <a href="/changeusername" class="hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
      <i class="ti ti-user mr-1 text-2xl"></i> change username
    </a>
  </h2>

  <!-- Link to change password page -->
  <h2 class="my-4">
    <a href="/changepassword" class="hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
      <i class="ti ti-password mr-1 text-2xl"></i> change password
    </a>
  </h2>

  <!-- Link to change profile picture page -->
  <h2 class="my-4">
    <a href="/changeprofilepicture" class="hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
      <i class="ti ti-photo mr-1 text-2xl"></i> change profile picture
    </a>
  </h2>

  <!-- Delete account section with reCAPTCHA if enabled -->
  <h2 class="my-4">
    {% if recaptcha %}
    <!-- Include reCAPTCHA scripts -->
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>

    <!-- Form with reCAPTCHA -->
    <form method="post" id="recaptchaForm">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
        class="g-recaptcha hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
        <i class="ti ti-user-x mr-1 text-2xl"></i>
        delete account
      </button>
    </form>
    {% else %}
    <!-- Form without reCAPTCHA -->
    <form method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <button type="submit" class="hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
        <i class="ti ti-user-x mr-1 text-2xl"></i>
        delete account
      </button>
    </form>
    {% endif %}
  </h2>
</div>
{% endblock body %}

templates/tailwindUI/adminPanel.html.jinja
{% extends 'layout.html.jinja' %}
{% block head %}
<!-- Set the title of the Admin Panel page -->
<title>Admin Panel</title>
{% endblock head %}

{% block body %}
<!-- Container for the Admin Panel content -->
<div class="w-fit mx-auto mt-32 text-center text-2xl font-medium">

  <!-- Link to the Users page in the Admin Panel -->
  <h1 class="my-4">
    <a href="admin/users" class="hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
      <i class="ti ti-users mr-1 text-2xl"></i> Users
    </a>
  </h1>

  <!-- Link to the Posts page in the Admin Panel -->
  <h1 class="my-4">
    <a href="admin/posts" class="hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
      <i class="ti ti-files mr-1 text-2xl"></i> Posts
    </a>
  </h1>

  <!-- Link to the Comments page in the Admin Panel -->
  <h1 class="my-4">
    <a href="admin/comments" class="hover:text-rose-500 duration-150 flex items-center w-fit mx-auto">
      <i class="ti ti-messages mr-1 text-2xl"></i> Comments
    </a>
  </h1>
</div>
{% endblock body %}

templates/tailwindUI/changeUserName.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Set the title of the page to "Change Username" -->
<title>Change Username</title>
{% endblock head %}

{% block body %}
<div class="text-center mt-32">
  {% if recaptcha %}
  <!-- Include Google reCAPTCHA scripts if recaptcha is enabled -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>
  <!-- Form for changing username with reCAPTCHA -->
  <form method="post" class="mx-auto w-fit mt-8" id="recaptchaForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- Include the form field for entering a new username -->
    {{ form.newUserName() }}
    <!-- Submit button with reCAPTCHA integration -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      change my username
    </button>
  </form>
  {% else %}
  <!-- Form for changing username without reCAPTCHA -->
  <form method="post" class="mx-auto w-fit mt-8">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- Include the form field for entering a new username -->
    {{ form.newUserName() }}
    <!-- Submit button without reCAPTCHA -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      change my username
    </button>
  </form>
  {% endif %}
</div>
{% endblock body %}

templates/tailwindUI/createPost.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Set the title of the page to "Create Post" -->
<title>Create Post</title>
{% endblock head %}

{% block body %}
<!-- Create Post Form Section -->
<div class="w-fit mx-auto mt-8">

  {% if recaptcha %}
  <!-- Include Google reCAPTCHA scripts -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>

  <!-- Form with reCAPTCHA enabled and enctype set for handling file uploads -->
  <form method="post" id="recaptchaForm" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Input fields for post title and tags -->
    {{ form.postTitle(autocomplete="off") }} {{ form.postTags(autocomplete="off") }}
    <p class="text-xs text-center w-fit mx-auto mb-2">(separate with commas)</p>

    <!-- Banner Upload Section -->
    <div class="w-72 mx-auto text-center mb-4">
      <label class="block mt-2 mb-1">Upload Banner</label>
      {{ form.postBanner(class_="") }}
    </div>

    <!-- Category Selection Section -->
    <div class="mx-auto w-fit">
      <label class="block my-1 text-center">Select a Category</label>
      {{ form.postCategory() }}
    </div>

    <!-- Post Content Section -->
    <div>
      {{ form.postContent(id_="editor", autocomplete="off") }}
    </div>

    <!-- Post Button Section -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium">
      Post
    </button>

  </form>
  {% else %}
  <!-- Form without reCAPTCHA, enctype set for handling file uploads -->
  <form method="post" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Input fields for post title and tags -->
    {{ form.postTitle(autocomplete="off") }} {{ form.postTags(autocomplete="off") }}
    <p class="text-xs text-center w-fit mx-auto mb-2">(separate with commas)</p>

    <!-- Banner Upload Section -->
    <div class="w-72 mx-auto text-center mb-4">
      <label class="block mt-2 mb-1">Upload Banner</label>
      {{ form.postBanner(class_="") }}
    </div>

    <!-- Category Selection Section -->
    <div class="mx-auto w-fit">
      <label class="block my-1 text-center">Select a Category</label>
      {{ form.postCategory() }}
    </div>

    <!-- Post Content Section -->
    <div>
      {{ form.postContent(id_="editor", autocomplete="off") }}
    </div>

    <!-- Post Button Section -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium">
      Post
    </button>

  </form>
  {% endif %}
</div>
<!-- End of Create Post Form Section -->
{% endblock body %}

templates/tailwindUI/csrfError.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Head block is intentionally left empty for this template -->
{% endblock head %}

{% block body %}
<div class="w-fit mx-auto text-center mt-16 text-lg">
  <!-- Display a message indicating the user should fill the form again -->
  <h1>Fill the same form again.</h1>
  <!-- Display the reason for filling the form again (supplied by the 'reason' variable) -->
  <p>Reason: {{ reason }}</p>
</div>
{% endblock body %}

templates/tailwindUI/dashboard.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Set the title dynamically based on the request path -->
{% if request.path == "/admin/posts" %}
<title>Admin Panel --> Posts</title>
{% else %}
<title>{{ session["userName"] }}'s Dashboard</title>
{% endif %}
{% endblock head %}

{% block body %}
<!-- Body Section -->
{% if showPosts %}
<!-- Display Posts Section -->
<h1 class="my-4 text-4xl font-medium select-none text-center">Posts</h1>

{% for post in posts %}
<!-- Individual Post Container -->
<div
  class="w-11/12 md:w-10/12 lg:w-8/12 xl:w-5/12 h-fit mx-auto py-4 px-2 my-8 border-2 rounded-md shadow-md border-gray-500/25">

  <!-- Post Banner -->
  <img src="{{ url_for('returnPostBanner.returnPostBanner', postID = post[0]) }}" class="w-96 rounded mx-auto" />

  <!-- Post Title with Link -->
  <a href="/post/{{ post[0] }}"
    class="text-rose-500 h-64 pb-8 text-2xl hover:text-rose-500/75 duration-150 select-none break-words">{{ post[1]
    }}</a>

  <!-- Post Content -->
  <div tag="content" class="h-60 overflow-y-hidden mt-6 mb-3 break-words">
    {{ post[3]|safe }}
  </div>

  <!-- Section: Edit/Delete Post -->
  <section class="flex items-center justify-between my-2">
    <a href="/editpost/{{ post[0] }}" class="hover:text-rose-500 duration-150 font-medium">
      <i class="ti ti-edit mr-1 text-2xl"></i>
    </a>
    <form method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <input type="hidden" name="postID" value="{{ post[0] }}" />
      <button type="submit" name="postDeleteButton" class="hover:text-rose-500 duration-150 font-medium">
        <i class="ti ti-trash-x mr-1 text-2xl"></i>
      </button>
    </form>
  </section>

  <!-- Section: Tags, Views, Creation Time, Last Edit Time -->
  <div class="flex items-center justify-between my-2">
    <div class="flex items-center">
      <i class="ti ti-tags mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Tags:</p>
      <p class="font-medium">{{ post[2] }}</p>
    </div>
    <div class="flex items-center">
      <i class="ti ti-eye mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Views:</p>
      <p class="font-medium">{{ post[6] }}</p>
    </div>
  </div>

  <!-- Section: Creation Time, Last Edit Time -->
  <div class="flex items-center justify-between my-2">
    <div class="flex items-center">
      <i class="ti ti-clock mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Creation Time:</p>
      <p class="time font-medium">{{ post[7] }}</p>
    </div>
    <div class="flex items-center">
      <i class="ti ti-clock-edit mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Last Edit Time:</p>
      <p class="time font-medium">{{ post[8] }}</p>
    </div>
  </div>

  <!-- Section: Creation Date, Last Edit Date -->
  <div class="flex items-center justify-between my-2">
    <div class="flex items-center">
      <i class="ti ti-calendar mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Creation Date:</p>
      <p class="date font-medium">{{ post[7] }}</p>
    </div>
    <div class="flex items-center">
      <i class="ti ti-calendar-dot mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Last Edit Date:</p>
      <p class="date font-medium">{{ post[8] }}</p>
    </div>
  </div>

  <!-- Section: Author, Category (if in admin/posts) -->
  <div class="flex items-center justify-between my-2">
    {% if request.path == "/admin/posts" %}
    <div class="flex items-center">
      <i class="ti ti-user mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Author:</p>
      <a href="/user/{{ post[5].lower() }}" class="hover:text-rose-500 duration-150 font-medium">{{ post[5] }}</a>
    </div>
    {% endif %}
    <div class="flex items-center">
      <i class="ti ti-category mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Category:</p>
      <p class="font-medium">{{ post[9] }}</p>
    </div>
  </div>

</div>
{% endfor %}

{% elif not showPosts %}
<!-- Display Message for No Posts -->
{% if request.path == "/admin/posts" %}
<h1>This user hasn't posted yet.</h1>
{% else %}
<p class="text-center mt-32 select-none">
  No post yet,
  <a href="/createpost" class="hover:text-rose-500 duration-150 font-medium">create one</a>?
</p>
{% endif %}
{% endif %}

<!-- Display Comments Section -->
{% if showComments and not request.path == "/admin/posts" %}
<h1 class="my-4 text-4xl font-medium select-none text-center">Comments</h1>

{% for comment in comments %}
<!-- Individual Comment Container -->
<div
  class="w-11/12 md:w-10/12 lg:w-3/4 xl:w-1/2 h-fit mx-auto py-4 px-2 my-8 border-2 rounded-md shadow-md border-gray-500/25">

  <!-- Comment Content -->
  <div tag="content">{{ comment[2] }}</div>

  <!-- Section: Creation Date, Creation Time -->
  <section class="flex items-center justify-between my-2">
    <div class="flex items-center">
      <i class="ti ti-calendar mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Creation Date:</p>
      <p class="date">{{ comment[4] }}</p>
    </div>
    <div class="flex items-center">
      <i class="ti ti-clock mr-1 text-xl"></i>
      <p class="hidden md:block mr-1">Creation Time:</p>
      <p class="time">{{ comment[4] }}</p>
    </div>
  </section>

  <!-- Link to Go to Post -->
  <a href="/post/{{ comment[1] }}" class="hover:text-rose-500 duration-150 font-medium">go to post</a>

</div>
{% endfor %}
{% endif %}

<!-- Back Button -->
{% if request.path == "/admin/posts" %}
<a href="/admin" class="hidden md:block fixed bottom-0 left-1">
  <i class="ti ti-arrow-back mr-1 text-xl hover:text-rose-500 duration-150"></i>
</a>
{% else %}
<a href='/user/{{ session["userName"] }}' class="hidden md:block fixed bottom-0 left-1">
  <i class="ti ti-arrow-back mr-1 text-xl hover:text-rose-500 duration-150"></i>
</a>
{% endif %}
{% endblock body %}

templates/tailwindUI/login.html.jinja
{% extends 'layout.html.jinja'%}
{%block head%}
<!-- Set the title of the page to "Login" -->
<title>Login</title>
<!-- End of the head block -->
{% endblock head %}
{%block body%}
<!-- Start of the body block -->
<div class="w-fit mx-auto mt-36 md:mt-52 text-center text-xl">
  {% if recaptcha %}
  <!-- Check if recaptcha is enabled -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>
  <!-- Create a form with recaptcha -->
  <form method="post" id="recaptchaForm">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- Render form fields for username and password with autocomplete turned off -->
    {{form.userName(autocomplete="off")}}{{form.password(autocomplete="off")}}
    <!-- Add the recaptcha button for login -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Login
    </button>
    <!-- Add a link for password reset -->
    <a href="/passwordreset/codesent=false" id="passwordReset"
      class="hover:text-rose-500 duration-150 text-sm font-normal select-none">Forgot password?</a>
  </form>
  {% else %}
  <!-- If recaptcha is not enabled, create a form without it -->
  <form method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <!-- Render form fields for username and password with autocomplete turned off -->
    {{form.userName(autocomplete="off")}}{{form.password(autocomplete="off")}}
    <!-- Add a button for login -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Login
    </button>
    <!-- Add a link for password reset -->
    <a href="/passwordreset/codesent=false" id="passwordReset"
      class="hover:text-rose-500 duration-150 text-sm font-normal select-none">Forgot password?</a>
  </form>
  {% endif %}
</div>
<!-- End of the body block -->
{% endblock body %}

templates/tailwindUI/signup.html.jinja
{% extends 'layout.html.jinja' %}

{% block head %}
<!-- Set the title of the page to "Signup" -->
<title>Signup</title>
{% endblock head %}

{% block body %}
<div class="w-fit mx-auto mt-24 md:mt-44 text-center text-xl">
  {% if recaptcha %}
  <!-- Include reCAPTCHA scripts if recaptcha is enabled -->
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <script src="{{ url_for('static', filename='js/recaptcha.js') }}"></script>

  <!-- Signup form with reCAPTCHA -->
  <form method="post" id="recaptchaForm" action="{{ url_for('signup.signup') }}">
    <!-- CSRF token for form security -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Form fields for username, email, password, and password confirmation -->
    {{form.userName(autocomplete="off")}}
    {{form.email(autocomplete="off")}}
    {{form.password()}}
    {{form.passwordConfirm()}}

    <!-- Signup button with reCAPTCHA integration -->
    <button type="submit" data-sitekey="{{ siteKey }}" data-callback="onSubmit" data-action="submit"
      class="g-recaptcha block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Signup
    </button>
  </form>
  {% else %}
  <!-- Signup form without reCAPTCHA -->
  <form method="post">
    <!-- CSRF token for form security -->
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

    <!-- Form fields for username, email, password, and password confirmation -->
    {{form.userName(autocomplete="off")}}
    {{form.email(autocomplete="off")}}
    {{form.password()}}
    {{form.passwordConfirm()}}

    <!-- Signup button without reCAPTCHA integration -->
    <button type="submit" class="block mx-auto m-2 hover:text-rose-500 duration-150 font-medium select-none">
      Signup
    </button>
  </form>
  {% endif %}

  <!-- App Privacy Policy warning text -->
  <div class="text-xs select-none">By signing up, you accept <a href="/privacyPolicy"
      class="font-medium text-rose-500 hover:text-rose-600 duration-150">Privacy Policy</a></div>
</div>
{% endblock body %}